In [2]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([6,7,5,4])
print(a+b)

[7 9 8 8]


In [5]:
m=np.array([[1,2,3],[4,5,6],[8,9,7]])
4*m

array([[ 4,  8, 12],
       [16, 20, 24],
       [32, 36, 28]])

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
a=np.array([[1,0,1,0],[0,1,1,0]],dtype='bool')
a

array([[ True, False,  True, False],
       [False,  True,  True, False]])

In [29]:
a=np.array([[1,0,5,0],[79,1,1,0]],dtype='float')
print(a.dtype)
a=a.astype('int32')
print(a.dtype)

float64
int32


In [30]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.array((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [35]:
a=5*np.ones(3,dtype='int32')
np.array((a,a))

array([[5, 5, 5],
       [5, 5, 5]])

In [48]:
a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)
a*a

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [46]:
a=np.array([4,6,1,8,3,9],dtype='int32')
print(a)
a.sort()
a

[4 6 1 8 3 9]


array([1, 3, 4, 6, 8, 9])

In [3]:
a=np.array([1,2,3,4,5,6,7,8,9,10,3,4,5,8,5],dtype='int32').reshape(5,3)
b=np.array([1,2,3,4,5,6],dtype='int32').reshape(3,2)
print(a)
print()
print(b)
np.dot(a,b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10  3  4]
 [ 5  8  5]]

[[1 2]
 [3 4]
 [5 6]]


array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [ 39,  56],
       [ 54,  72]])

In [5]:
a.index(5)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [7]:
a=np.random.randint(10,size=(3,5,6,4,3))

In [8]:
a

array([[[[[5, 7, 8],
          [3, 3, 1],
          [2, 3, 0],
          [3, 0, 6]],

         [[2, 2, 9],
          [2, 1, 2],
          [1, 3, 0],
          [7, 9, 5]],

         [[2, 9, 8],
          [0, 7, 6],
          [7, 4, 1],
          [5, 6, 8]],

         [[8, 8, 8],
          [9, 8, 1],
          [2, 8, 9],
          [2, 4, 4]],

         [[4, 2, 2],
          [3, 9, 9],
          [9, 8, 8],
          [9, 8, 7]],

         [[9, 4, 7],
          [3, 6, 4],
          [1, 9, 7],
          [3, 9, 7]]],


        [[[4, 4, 2],
          [0, 1, 7],
          [8, 3, 3],
          [7, 9, 1]],

         [[6, 8, 7],
          [9, 8, 8],
          [3, 9, 5],
          [2, 9, 8]],

         [[9, 5, 4],
          [3, 2, 8],
          [4, 5, 9],
          [2, 2, 9]],

         [[5, 3, 3],
          [2, 4, 7],
          [8, 0, 6],
          [2, 9, 3]],

         [[1, 1, 8],
          [2, 1, 8],
          [6, 3, 0],
          [3, 8, 5]],

         [[3, 5, 7],
          [3, 7, 8],
          

In [16]:
a[-1,-1,-1,-2:,-1]

array([7, 8])

# Assignment 2

1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array. 

In [1]:
import numpy as np
a=[1,2,3,4]
np.array(a)

array([1, 2, 3, 4])

2. Write a NumPy program to create a 4x4 matrix with values ranging from 7 to 15. 

In [8]:
np.random.randint(low=7,high=16,size=(3,2,2,3))

array([[[[ 9, 15,  9],
         [11, 11, 14]],

        [[15, 14, 11],
         [12, 11,  7]]],


       [[[ 7, 15,  8],
         [14, 13, 12]],

        [[10,  9, 11],
         [10, 15, 11]]],


       [[[10, 15, 11],
         [14,  8, 12]],

        [[ 9,  9, 14],
         [13, 12, 11]]]])

3. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

In [13]:
a=np.zeros(10,dtype='int32')
a[5]=11
a

array([ 0,  0,  0,  0,  0, 11,  0,  0,  0,  0])

4. Write a NumPy program to reverse an array (first element becomes last).

In [18]:
a=[1,2,3,4,5,6]
a=np.array(a)
b=[]
for i in range(len(a)-1,-1,-1):
    b.append(a[i])
np.array(b)

array([6, 5, 4, 3, 2, 1])

5. Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [25]:
a=np.zeros(9,dtype='int32')
a=a.reshape(3,3)
np.pad(a,1,constant_values=1)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

6. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [35]:
np.array((([0,1]*4)+[1,0]*4)*4).reshape(8,8)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

7. Write a NumPy program to append values to the end of an array.

In [38]:
a=8
b=np.array([1,2,3,4,5])
np.append(b,a)

array([1, 2, 3, 4, 5, 8])

8. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees and vice versa. Values are stored into a NumPy array.

In [90]:
a=np.arange(0,16).reshape(4,4)
a,a+273

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[273, 274, 275, 276],
        [277, 278, 279, 280],
        [281, 282, 283, 284],
        [285, 286, 287, 288]]))

9. Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [73]:
a.size,a.itemsize,a.nbytes

(16, 4, 64)

10. Write a NumPy program to test whether each element of a 1-D array is also present in a second array

In [81]:
 for i in b:
    if i in a:
        print('yes')
    else:
        print('no')

yes
yes
yes
yes
yes


11. Write a NumPy program to create an array of ones and an array of zeros.

In [82]:
np.ones(10),np.zeros(5)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), array([0., 0., 0., 0., 0.]))

12. Write a NumPy program to create a new shape to an array without changing its data

In [85]:
print(a)
a=a.reshape(2,2,2,2)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


13. Write a NumPy program to change the data type of an array.

In [91]:
print(a.dtype)
a=a.astype('float64')
print(a.dtype)

int32
float64


14. Write a NumPy program to create a new array of 3*5, filled with 2.

In [93]:
b=np.ones(15).reshape(3,5)
print(b*1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


15. Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere

In [99]:
c=np.eye(4)
c=np.array((c,c,c))
c

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]])