In [4]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([6,7,5,4])
print(a+b)

[7 9 8 8]


In [5]:
m=np.array([[1,2,3],[4,5,6],[8,9,7]])
4*m

array([[ 4,  8, 12],
       [16, 20, 24],
       [32, 36, 28]])

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
a=np.array([[1,0,1,0],[0,1,1,0]],dtype='bool')
a

array([[ True, False,  True, False],
       [False,  True,  True, False]])

In [29]:
a=np.array([[1,0,5,0],[79,1,1,0]],dtype='float')
print(a.dtype)
a=a.astype('int32')
print(a.dtype)

float64
int32


In [30]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.array((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [35]:
a=5*np.ones(3,dtype='int32')
np.array((a,a))

array([[5, 5, 5],
       [5, 5, 5]])

In [48]:
a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)
a*a

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [46]:
a=np.array([4,6,1,8,3,9],dtype='int32')
print(a)
a.sort()
a

[4 6 1 8 3 9]


array([1, 3, 4, 6, 8, 9])

In [51]:
a=np.array([1,2,3,4,5,6,7,8,9,10,3,4,5,8,5],dtype='int32').reshape(5,3)
b=np.array([1,2,3,4,5,6],dtype='int32').reshape(3,2)
print(a)
print()
print(b)
np.dot(a,b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10  3  4]
 [ 5  8  5]]

[[1 2]
 [3 4]
 [5 6]]


array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [ 39,  56],
       [ 54,  72]])